language: groovy
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
before_install:
- chmod +x gradlew
deploy:
edge:
  source: travis-ci/dpl
  branch: ps-fix-anynines-url
  provider: anynines
  username: james.b.northrop@googlemail.com
  password: nnNZAPjoOY2QMvB5pPO1mO9S/1/+d8AjQCVUKBoavyFN4CrQrQgw3bo9uLnBdsWdqRAtIURmf8EkTJT0NcN7ldp6ee0bCWzDFZhRuwJr7/3nRF/st2vnFacSxmz2SxaDJtGstV1tfLWbV4//zsWVMCTrVUpfcwow/d5FFDiwzIVu3yE9YM6LVJHoaZBH+QlNU6hhD7CcN39c9Z5nRDfRAQx15lJ49xGXmwwjuNIZBHTcPHLjRvCLd8MNPm/XD+c7I8Ep/OH88bDTRhIQXGha5ktBj+NmHglY1dBUgmEZ1KSVRymZqDmg/cS6mQRMVW/dguoVJ22OdU8hqKwLdol+PMb8fcRSwTWn7vBOY7vPw69Ev8Qsq4OxgPs3mr+qBnvEYwLZcvBHSUl4Iycq+LesvALnt6H0LZmC+GuJuSMe4qcwdhSmA2BTewZQcBkCJj1CBPPrOiepZav8D44BBnz4y4H84Ze2Ao9rASHNj4Ih0eHmF/d5sx8uhgwJ3B64n6/49HYMDzo16zBE5It8RpIPrQjXpjeWfobXWTJJB+/MvtRVeWSi5rAayxU+bFdGkQorAOJh82yjiM2B0eG0cBKd3V1+GSwiEM85c9rTH84V27BvEBRXJ1LrWeDxXYyTcsUil4USD/m1twf3X5aNfEuS9Iv3G6MrYqKadmAhAG+yqgw=
  organization: james_b_northrop_googlemail_com
  space: test
